var dinosaurs = [
  {
    name: 'Tyrannosaurus Rex', 
    legs: 2,
    type: 'carnivore'
  },
  {
    name: 'Stegosaurus',
    legs: 4,
    type: 'herbivore'
  },
  {
    name: 'Triceratops',
    legs: 4,
    type: 'herbivore'
  },
  {
    name: 'Pachycephalosaurus',
    legs: 2,
    type: 'herbivore'
  }
]
var dinosaurs = [
  {
    name: 'Tyrannosaurus Rex', 
    legs: 2,
    type: 'carnivore'
  },
  {
    name: 'Stegosaurus',
    legs: 4,
    type: 'herbivore'
  },
  {
    name: 'Triceratops',
    legs: 4,
    type: 'herbivore'
  },
  {
    name: 'Pachycephalosaurus',
    legs: 2,
    type: 'herbivore'
  }
]
