var dinosaurs = [
  {
    name: 'Tyrannosaurus Rex', 
    legs: 2,
    type: 'carnivore',
    period: 'Cretaceous'
  },
  {
    name: 'Ceratosaurus',
    legs: 2,
    type: 'carnivore',
    period: 'Jurassic'
  },
  {
    name: 'Stegosaurus',
    legs: 4,
    type: 'herbivore',
    period: 'Jurassic'
  },
  {
    name: 'Eoraptor',
    legs: 4,
    type: 'carnivore',
    period: 'Triassic'
  },
  {
    name: 'Triceratops',
    legs: 4,
    type: 'herbivore',
    period: 'Cretaceous'
  },
  {
    name: 'Pachycephalosaurus',
    legs: 2,
    type: 'herbivore',
    period: 'Cretaceous'
  }
]

// write a function that returns an array containing 
// the names of all the four-legged herbivores.

// write a function that returns an array containing
// the names of all the n-legged herbivores

// write a function that returns the total number of
// legs of all the dinosaurs

// write a function that returns an array containing 
// the names of all the herbivores preyed upon by a 
// given carnivore 
